const userData = [
  { choice: "A", value: "Administrative Services" },
  { choice: "B", value: "AdTech" },
  { choice: "C", value: "Aerospace & Defence" },
  { choice: "D", value: "AgriTech" },
  { choice: "E", value: "Analytics & BI" },
  { choice: "F", value: "Animation & Filmography" },
  { choice: "G", value: "Art & Design" },
  { choice: "H", value: "Automotive" },
  { choice: "I", value: "Biotech" },
  { choice: "J", value: "Blockchain" },
  { choice: "K", value: "Clothing & Apparel" },
  { choice: "L", value: "Collaboration" },
  { choice: "M", value: "Communication" },
  { choice: "N", value: "Community" },
  { choice: "O", value: "Construction" },
  { choice: "P", value: "Consumer Service" },
  { choice: "Q", value: "Consumer Electronics" },
  { choice: "R", value: "Content" },
  { choice: "S", value: "Cryptocurrency" },
  { choice: "T", value: "DeepTech" },
  { choice: "U", value: "Design" },
  { choice: "V", value: "Direct-To-Consumer Brands" },
  { choice: "W", value: "E-Commerce" },
  { choice: "X", value: "EdTech" },
  { choice: "Y", value: "Energy" },
  { choice: "Z", value: "Enterprise Tech" },
  { choice: "AA", value: "Entertainment" },
  { choice: "AB", value: "Events" },
  { choice: "AC", value: "Fintech" },
  { choice: "AD", value: "FMCG" },
  { choice: "AE", value: "FoodTech" },
  { choice: "AF", value: "Gamming" },
  { choice: "AG", value: "Government & Military" },
  { choice: "AH", value: "Hardware" },
  { choice: "AI", value: "HealthTech/MedTech/Healthcare" },
  { choice: "AJ", value: "Hospitality" },
  { choice: "AK", value: "Hyperlocal" },
  { choice: "AL", value: "Iaas" },
  { choice: "AM", value: "Insurance" },
  { choice: "AN", value: "Life Science" },
  { choice: "AO", value: "Logistics" },
  { choice: "AP", value: "Machine Learning" },
  { choice: "AQ", value: "Manufacturing" },
  { choice: "AR", value: "Marketplace" },
  { choice: "AS", value: "MarTch" },
  { choice: "AT", value: "Media" },
  { choice: "AU", value: "Mobility/Transportation" },
  { choice: "AV", value: "Music & Audio" },
  { choice: "AW", value: "PaaS" },
  { choice: "AX", value: "Public Policy" },
  { choice: "AY", value: "Real Estate" },
  { choice: "AZ", value: "Recruitment" },
  { choice: "BA", value: "Retail" },
  { choice: "BB", value: "Robotics" },
  { choice: "BC", value: "SaaS" },
  { choice: "BD", value: "Security" },
  { choice: "BE", value: "Services" },
  { choice: "BF", value: "Social Media" },
  { choice: "BG", value: "Software" },
  { choice: "BH", value: "SpaceTech" },
  { choice: "BI", value: "Technology" },
  { choice: "BJ", value: "Tourism" },
  { choice: "BK", value: "Travel" },
  { choice: "BL", value: "Other" },
];

export default userData;
